### PR TITLE
Refactor error codes in qs akka

### PR DESCRIPTION
**Pull request by ducanhkhu-ovo**
Move all magic strings to `val`

### CODE REVIEW

**Comment by stuartizon** [comment]
This looks pretty good, but I'd like us to make sure there's nothing depending on those values in FE or BE services, where you are changing spaces to underscores

**Comment by ducanhkhu-ovo** [comment]
versioning of the lib should take care of that shouldn't it?

**Comment by stuartizon** [comment]
Possibly. I'm more thinking about clients of any services we upgrade to use this version.

**Comment by stuartizon** [comment]
Looks like you need to fix a merge conflict here...

**Comment by ducanhkhu-ovo** [comment]
fixed conflicts

**Pull request merged**
